### ISSUE TITLE
bpy.ops.object.select_by_layer could not be found

### ISSUE THREAD

**Issue by mixmixmix** [njanakiev/blender-scripting-intro#6]
While calling most of the utility functions I get errors like the following. I use NixOS so it might be due to unusual libraries locations, but shouldn't really.

Any ideas?

```
Traceback (most recent call last):
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/mix/repos/blender-scripting/scripts/utils/__init__.py", line 129, in removeAll
  File "/nix/store/lbd3a6hzkjkljyy03y5rsfaf9ih325dp-blender-2.80/share/blender/2.80/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.object.select_by_layer" error, could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/lbd3a6hzkjkljyy03y5rsfaf9ih325dp-blender-2.80/share/blender/2.80/scripts/modules/console_python.py", line 168, in execute
    is_multiline = console.push(line_exec)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/code.py", line 258, in push
    more = self.runsource(source, self.filename)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/code.py", line 74, in runsource
    self.runcode(code)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/code.py", line 94, in runcode
    self.showtraceback()
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/code.py", line 142, in showtraceback
    lines = traceback.format_exception(ei[0], ei[1], last_tb.tb_next)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 3495: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/lbd3a6hzkjkljyy03y5rsfaf9ih325dp-blender-2.80/share/blender/2.80/scripts/startup/bl_operators/console.py", line 55, in execute
    return execute(context, self.interactive)
  File "/nix/store/lbd3a6hzkjkljyy03y5rsfaf9ih325dp-blender-2.80/share/blender/2.80/scripts/modules/console_python.py", line 172, in execute
    stderr.write(traceback.format_exc())
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 521, in __init__
    self._load_lines()
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 533, in _load_lines
    self.__context__._load_lines()
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 531, in _load_lines
    frame.line
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 3495: invalid start byte

location: <unknown location>:-1

```

**Comment by Xaldew** [comment]
I ran into that particular error as well a few days ago. Are you using Blender >= 2.81?

In my case I could resolve this by replacing `bpy.ops.object.select_by_layer` with `bpy.ops.object.select_all(action="SELECT")` in `script/utils/__init__.py.` I'm not exactly sure if this is correct, but it seems to work. There are however other problems with running on a recent blender, e.g., the lighting seems to work differently.

My suggestion would be to revert a slightly older Blender version if you want to try out these examples, at least until this repo has been updated.

**Comment by myselfhimself** [comment]
Reproduced with blender 2.81

**Comment by myselfhimself** [comment]
your "SELECT" line solved it
now ao_blend_type has been removed in blender 2.80 https://docs.blender.org/api/current/change_log.html#id332 (when running fisher_iris_visualization.py)

**Comment by jeffheaton** [comment]
Also getting this error.  I guess a "breaking change" in later Blenders.

**Comment by njanakiev** [comment]
The scripts are updated now for Blender 2.8+, all of the scripts should be working again.
